client/src/pages/NewOrganisationInvitation.jsx

Moved the message input field to below the 'invitee' input field like in other invitation forms

[Fixed #168336451] Switched the 'message' input field 

---

.travis.yml
server/test/abstract_test.py
server/test/api/test_collaboration.py

Only first stage was run, so coverage, python tests and yarn build was skipped, for unknown reasons.  Restructured the travis file and now everything seems to work again.

Fix travis stages

---

server/__main__.py
server/api/base.py
server/config/test_config.yml
server/mqtt.py
server/requirements/base.txt

Thanks for taking care of the test!

Add MQTT Service Bus functionality

---

server/api/plsc.py
server/test/api/test_plsc.py

Add Collaboration website_url attribute to PLSC API result

Plsc add co url

---

.gitignore
client/src/components/redesign/OrganisationInvitations.jsx
client/src/components/redesign/ServicesWithoutAdmin.jsx
client/src/components/redesign/ServicesWithoutAdmin.scss
client/src/locale/en.js
client/src/locale/nl.js
client/src/pages/System.jsx
server/api/system.py
server/test/api/test_system.py

Added a section to the system actions tab for services without administrators

---

client/src/api/index.js
client/src/pages/App.jsx
server/api/pam_websso.py
server/auth/urls.py
server/test/api/test_pam_websso.py

Only externally visible paths for now.

Rename pam-websso to pam-weblogin

---

.gitignore
server/api/pam_websso.py
server/test/api/test_pam_websso.py

Needs https://github.com/SURFscz/pam-weblogin/pull/11

Rename debug_msg to info, fix info messages

---

client/src/components/CheckBox.scss

Firefox to the left, Chrome to the right.

Squared the checkboxes

---

client/src/components/redesign/Collaborations.jsx
client/src/locale/en.js
client/src/locale/nl.js

Updated translation: label filter

---

.github/workflows/main.yml
server/__main__.py
server/config/test_config.yml
server/migrations/alembic.ini
server/requirements/base.txt

Replace MySQL driver, needed by https://github.com/SURFscz/SRAM-deploy/pull/368

Use mysqlclient instead of PyMySQL

---

server/Dockerfile
server/api/scim.py
server/requirements/base.txt
server/scim/group_template.py
server/scim/resource_type_template.py
server/scim/schema_template.py
server/scim/user_template.py
server/test/api/test_mock_scim.py
server/test/api/test_scim.py

Added support for custom SRAM attributes to make SRAM SCIM compatible with SRAM LDAP

SCIM sram schema

---

client/src/locale/en.js
client/src/locale/nl.js
client/src/pages/SecondFactorAuthentication.jsx

Updated translation: 2fa reset

---

client/src/locale/en.js
client/src/pages/OrganisationForm.jsx

Update translation and form order

---

.github/workflows/main.yml
Dockerfile

Build SBS server image in SBS repo

Build server image

---

server/api/pam_websso.py

Add 'id' to group details that holds the Collaboration immutable identifier.

#1419 add entitlements to pam weblogin verify response

---

server/api/user_saml.py
server/test/api/test_user_saml.py

New users who have not yet logged in the SBS but are trying to access a free-ride service need to be redirected to SBS in order to be provisioned.  We redirect them to the AUP endpoint (as we are sure they need to go there anyway).
Add a new `status` parameter to the call so we dan distinguish between "regular" AUP users and users who ar eaccessing a free-ride service. (see #1463 for why that is neccessary)

Redirect new users trying to login to a freeride server to SBS 

---

server/scim/sweep.py
server/test/scim/test_sweep.py

Now tests for differences in links as well.
also adjusted SBS tests for this

Fix Sweep changes SRAM Group exention links

---

server/scim/schema_template.py
server/scim/sweep.py
server/scim/user_template.py
server/test/scim/test_sweep.py
server/test/scim/test_user_template.py

Issue 1631

---

server/cron/scim_sweep_services.py
server/scim/sweep.py

Fix for findings during acceptance test for issue 1593

---

server/mail.py
server/templates/suspend_delete_warning_notification.html
server/templates/suspend_suspend_notification.html

Sbs 1617 suspend delete email language

---

server/auth/mfa.py
server/config/test_config.yml
server/test/auth/test_mfa.py

allow multiple sho per idp (fixes: #1716)

---

server/cli.py
server/test/stress_seed.py
server/test/test_seed.py

The CLI commands are now covered with tests

added tests for seed cli commands
